CREATE or REPLACE FUNCTION HASH_MD5
(
  psINPUT IN VARCHAR2
) RETURN VARCHAR2 AS rHash RAW (16);
BEGIN
    rHash := DBMS_CRYPTO.HASH (TO_CLOB (psINPUT), DBMS_CRYPTO.HASH_MD5);
    RETURN (LOWER (RAWTOHEX (rHash)));
END HASH_MD5;